# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Tue, 16 Aug 2022 12:37:48 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

#admin:$argon2id$v=19$m=65536,t=4,p=1$eGY4Vm1NYnpGdzV3UEhIQQ$40glnWxRYoLjy/dMEmmxpT1nmy1ZAK1jaOaxCaePGBs:admin:admin@localhost:admin
#deleteme:$1$4fd0ad31$.cId7p1uxI4a.RcrH810n0:-:-:admin,user
admin:$1$ywSXOpt7$SwmugLd8NMbNpIjRj2h4c.:admin:admin@localhost:admin
